describe("firstRecDMB", () => {
  it("tests firstRecDMB", async () => {
    // await browser.setWindowSize(753, 645)
    await browser.url("https://demoblaze.com/index.html")
    await expect(browser).toHaveUrl("https://demoblaze.com/index.html")
    await browser.$("//*[@id=\"login2\"]").click()
    await browser.$("//*[@id=\"loginusername\"]").click()
    await browser.$("//*[@id=\"loginusername\"]").setValue("aswar")
    await browser.$("//*[@id=\"loginpassword\"]").click()
    await browser.$("//*[@id=\"loginpassword\"]").setValue("12345")
    await browser.$("//*[@id=\"logInModal\"]/div/div/div[3]/button[2]").click()
    await browser.$("text/Iphone 6 32gb").click()
    await expect(browser).toHaveUrl("https://demoblaze.com/prod.html?idp_=5")
    await browser.$("//*[@id=\"tbodyid\"]/div[2]/div/a").click()
    await browser.$("//*[@id=\"cartur\"]").click()
    await expect(browser).toHaveUrl("https://demoblaze.com/cart.html")
    await browser.$("//*[@id=\"page-wrapper\"]/div/div[2]/button").click()
    await browser.$("//*[@id=\"name\"]").click()
    await browser.$("//*[@id=\"name\"]").setValue("azwar")
    await browser.$("//*[@id=\"country\"]").click()
    await browser.$("//*[@id=\"country\"]").setValue("Wakanda")
    await browser.$("//*[@id=\"city\"]").click()
    await browser.$("//*[@id=\"city\"]").setValue("Polman")
    await browser.$("//*[@id=\"card\"]").click()
    await browser.$("//*[@id=\"card\"]").setValue("334411")
    await browser.$("//*[@id=\"month\"]").click()
    await browser.$("//*[@id=\"month\"]").setValue("Januari")
    await browser.$("//*[@id=\"orderModal\"]/div/div/div[2]/form/div[6]").click()
    await browser.$("//*[@id=\"year\"]").click()
    await browser.$("//*[@id=\"year\"]").setValue("2024")
    await browser.$("//*[@id=\"orderModal\"]/div/div/div[3]/button[2]").click()
  });
});